#!/bin/sh

cd /home/admin

set -e

export PACKAGE_NAME=${PACKAGE_NAME:-org.woltage.irssiconnectbot}

export HOME=/home/admin
export PATH=$PATH:/home/admin/droid/bin

for ARCH_NAME in arm x86 mips; do
  export ARCH_NAME
  for i in ncurses-5.9 protobuf-2.4.1 openssl; do
    cd $i
    if [ -f Makefile ]; then
      make clean
    fi
    opkg-buildirssi
    cd ..
  done
done

mkdir -p /target/share/terminfo/ /target/bin

# keep this for the /.../share/terminfo/ files
cp ncurses_*_arm.ipk /target

rm -rf data
mkdir data

cd data
rm -f *.tar.gz
ar x ../ncurses_*_arm.ipk
tar zxf data.tar.gz
cd ..
mv data/data/data/$PACKAGE_NAME/files/share/terminfo/{s/screen,v/vt100,x/xterm,x/xterm-color,x/xterm-256color,a/ansi} /target/share/terminfo/

for ARCH_NAME in arm x86 mips; do
  export ARCH_NAME
  rm -rf ~/droid/data
  opkg-extract-devel-irssi ncurses-devel_*_$ARCH_NAME.ipk
  opkg-extract-devel-irssi openssl-devel_*_$ARCH_NAME.ipk
  opkg-extract-devel-irssi protobuf-devel_*_$ARCH_NAME.ipk

  # only use static linking for our libs, android dynamic linking outside of /system/lib isn't fun
  rm ~/droid/data/data/$PACKAGE_NAME/files/lib/*.so

  for WANT_PIE in pie nopie; do
    export WANT_PIE
    cd mosh
    if [ -f Makefile ]; then
      make clean
    fi
    opkg-buildirssi
    cd ..
    PKGNAME=`ls mosh_*_$ARCH_NAME.ipk`
    cp $PKGNAME /target/$PKGNAME-$WANT_PIE

    rm -rf data
    mkdir data

    cd data
    rm -f *.tar.gz
    ar x ../$PKGNAME
    tar zxf data.tar.gz
    cd ..

    mv data/data/data/$PACKAGE_NAME/files/bin/mosh-client /target/bin/mosh-client.$ARCH_NAME.$WANT_PIE
  done
done
